[Accent]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[AERO]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[Desktop]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ActiveCaption]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ActiveCaptionGradient]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[InActiveCaption]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[InActiveCaptionGradient]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[CaptionText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[InActiveCaptionText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ActiveBorder]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[InActiveBorder]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[Highlight]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[HighlightText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[3DDarkShadow]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[3DLight]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[GrayText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ButtonFace]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ButtonText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ButtonHighlight]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ButtonShadow]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[Menu]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[MenuText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[MenuBar]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[MenuHighlight]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[Window]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[WindowFrame]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[WindowText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ToolTipBackground]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[ToolTipText]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[AppWorkspace]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[Scrollbar]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[Hyperlink]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[WIN8]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[DWM_COLOR]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[DWM_AFTERGLOW_COLOR]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
Hex=#Hex#
DynamicVariables=1

[DWM_COLOR_BALANCE]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
DynamicVariables=1

[DWM_AFTERGLOW_BALANCE]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
DynamicVariables=1

[DWM_BLUR_BALANCE]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
DynamicVariables=1

[DWM_GLASS_REFLECTION_INTENSITY]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
DynamicVariables=1

[DWM_OPAQUE_BLEND]
Measure=Plugin
Plugin=SysColor
ColorType=#CURRENTSECTION#
DisplayType=#Type#
DynamicVariables=1

[isHex]
Measure=Calc
Formula=#Hex#
IfCondition=isHex=1
IfTrueAction=[!SetOption Hex FontColor [Accent]][!SetOption Dec FontColor ""]
IfFalseAction=[!SetOption Hex FontColor ""][!SetOption Dec FontColor [Accent]]
DynamicVariables=1
